# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-package:
        name: upgrader
        environment:
            flutter: stable
        scripts:
            - flutter doctor
            - flutter packages pub get
            - dart format --set-exit-if-changed ./lib ./test ./example
            - flutter test
