# Copyright (c) 2023 Larry Aasen. All rights reserved.

name: platforms

defaults:
  run:
    working-directory: example

on:
  workflow_dispatch:

jobs:
  test-platform:
    strategy:
      matrix:
        runs-on-name: ['windows-latest']
        flutter-version: ['3.3.12']

    runs-on: ${{ matrix.runs-on-name }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.flutter-version }}'
          channel: 'stable'

      - name: Get flutter packages
        run: flutter pub get

      - name: Run the driver test
        run: 	cd example; flutter drive --target=test/driver_test/driver.dart --driver=test/driver_test/driver_test.dart

      - name: Upload Screenshots to Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-platform-${{ matrix.runs-on-name }}-${{ matrix.flutter-version }}
          path: example/test/driver_test/screenshots/*
